/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Marlon Ramirez
 */
public class Acerca extends javax.swing.JInternalFrame {

    /**
     * Creates new form Acerca
     */
    public Acerca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lProg = new javax.swing.JLabel();
        lMarlie = new javax.swing.JLabel();
        lGerald = new javax.swing.JLabel();
        lIlse = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 248, 239));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Acerca de ...");

        lProg.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        lProg.setForeground(new java.awt.Color(58, 38, 29));
        lProg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lProg.setText("Programadores");

        lMarlie.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lMarlie.setForeground(new java.awt.Color(58, 38, 29));
        lMarlie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lMarlie.setText("Marlie Lucía Ramírez Altamirano");

        lGerald.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lGerald.setForeground(new java.awt.Color(58, 38, 29));
        lGerald.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lGerald.setText("Gerald José Diaz Mairena");

        lIlse.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lIlse.setForeground(new java.awt.Color(58, 38, 29));
        lIlse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lIlse.setText("Ilse Michelle Gomez Bermudez");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lMarlie, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addComponent(lGerald, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lIlse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lProg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lProg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lMarlie)
                .addGap(30, 30, 30)
                .addComponent(lGerald)
                .addGap(30, 30, 30)
                .addComponent(lIlse)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lGerald;
    private javax.swing.JLabel lIlse;
    private javax.swing.JLabel lMarlie;
    private javax.swing.JLabel lProg;
    // End of variables declaration//GEN-END:variables
}
