/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyectofinal.Venta;
import proyectofinal.Pasteleria;

/**
 *
 * @author Marlon Ramirez
 */
public class VentaInt extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venta
     */
    public VentaInt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollBar1 = new javax.swing.JScrollBar();
        jSpinner1 = new javax.swing.JSpinner();
        jProgressBar1 = new javax.swing.JProgressBar();
        jComboBox2 = new javax.swing.JComboBox<>();
        jProgressBar2 = new javax.swing.JProgressBar();
        lProducto = new javax.swing.JLabel();
        lFecha1 = new javax.swing.JLabel();
        lCantidad = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        bIngresar = new javax.swing.JButton();
        cbProducto = new javax.swing.JComboBox<>();
        tfFecha = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(255, 248, 239));
        setClosable(true);
        setTitle("Venta");

        lProducto.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        lProducto.setText("Producto Vendido:");

        lFecha1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        lFecha1.setText("Fecha de Venta:");

        lCantidad.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        lCantidad.setText("Cantidad:");

        bIngresar.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        bIngresar.setForeground(new java.awt.Color(58, 38, 29));
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        cbProducto.setBackground(new java.awt.Color(255, 248, 239));
        cbProducto.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        cbProducto.setForeground(new java.awt.Color(58, 38, 29));
        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pastel de Zanahoria", "Pastel de Fresas con Crema", "Pastel de Red Velvet", "Pastel de Moka", "Pastel de Chocolate", "Galleta Chocolate Chips", "Galleta de Avena", "Galleta de Red Velvet", "Pay de Limón", "Pay de Manzana", "Tartaleta de Frutas", "Brownie und.", "Torre de Brownies", "Tres Leches", "Cheesecake Clasico", "Cheesecake Calala" }));

        tfFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFecha.setForeground(new java.awt.Color(102, 102, 102));
        tfFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFecha.setText("Año - Mes - Dia");
        tfFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lFecha1)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lProducto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(62, 62, 62)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfCantidad)
                    .addComponent(cbProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, 232, Short.MAX_VALUE)
                    .addComponent(tfFecha))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(bIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProducto)
                    .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCantidad)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
         Venta v = new Venta(
                tfFecha.getText(),
                cbProducto.getText(),
                Integer.parseInt(tfCantidad.getText())
        );
        Pasteleria p;
        try {
            p = new Pasteleria();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentaInt.class.getName()).log(Level.SEVERE, null, ex);
        }
        int result = p.registrarCiudad(v.getFechaVenta(), v.getNombre(), v.getCantidad(), v.getPrecio(), v.getMontoFinal());
        if (result !=0){
            JOptionPane.showMessageDialog(this, "Registro guardado");
        }else{
            JOptionPane.showMessageDialog(this, "Registro no guardado");
        }
                                            
    }//GEN-LAST:event_bIngresarActionPerformed

    private void tfFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lCantidad;
    private javax.swing.JLabel lFecha1;
    private javax.swing.JLabel lProducto;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfFecha;
    // End of variables declaration//GEN-END:variables
}
